import { Injectable } from '@angular/core';

import { Order } from '../models/order.model';

const d = (s: string) => new Date(s);

const ORDERS: (Omit<Order, 'active'> & { active?: boolean })[] = [
  {
    id: 10001,
    customerName: 'Marie Lambert',
    customerEmail: 'marie.lambert@mail.fr',
    date: d('2026-08-20'),
    status: 'pending',
    total: 129.9,
    items: 2,
    country: 'France',
  },
  {
    id: 10002,
    customerName: 'Thomas Martin',
    customerEmail: 'thomas.martin@mail.fr',
    date: d('2026-08-19'),
    status: 'processing',
    total: 349.0,
    items: 4,
    country: 'France',
  },
  {
    id: 10003,
    customerName: 'Emma Wilson',
    customerEmail: 'emma.wilson@mail.co.uk',
    date: d('2026-08-18'),
    status: 'shipped',
    total: 89.5,
    items: 1,
    country: 'UK',
  },
  {
    id: 10004,
    customerName: 'Klaus Weber',
    customerEmail: 'k.weber@mail.de',
    date: d('2026-08-17'),
    status: 'delivered',
    total: 514.99,
    items: 6,
    country: 'Allemagne',
  },
  {
    id: 10005,
    customerName: 'Maria Garcia',
    customerEmail: 'maria.garcia@mail.es',
    date: d('2026-08-16'),
    status: 'cancelled',
    total: 74.99,
    items: 1,
    country: 'Espagne',
    active: false,
  },
  {
    id: 10006,
    customerName: 'Sophie Bernard',
    customerEmail: 'sophie.b@mail.be',
    date: d('2026-08-15'),
    status: 'delivered',
    total: 212.4,
    items: 3,
    country: 'Belgique',
  },
  {
    id: 10007,
    customerName: 'Pierre Dubois',
    customerEmail: 'pierre.dubois@mail.fr',
    date: d('2026-08-14'),
    status: 'delivered',
    total: 67.0,
    items: 2,
    country: 'France',
  },
  {
    id: 10008,
    customerName: 'Anna Schmidt',
    customerEmail: 'anna.schmidt@mail.de',
    date: d('2026-08-13'),
    status: 'shipped',
    total: 189.95,
    items: 3,
    country: 'Allemagne',
  },
  {
    id: 10009,
    customerName: 'Carlos Lopez',
    customerEmail: 'c.lopez@mail.es',
    date: d('2026-08-12'),
    status: 'processing',
    total: 430.0,
    items: 5,
    country: 'Espagne',
  },
  {
    id: 10010,
    customerName: 'Giulia Rossi',
    customerEmail: 'giulia.rossi@mail.it',
    date: d('2026-08-11'),
    status: 'pending',
    total: 95.0,
    items: 2,
    country: 'Italie',
  },
  {
    id: 10011,
    customerName: 'James Brown',
    customerEmail: 'james.brown@mail.co.uk',
    date: d('2026-08-10'),
    status: 'delivered',
    total: 310.5,
    items: 4,
    country: 'UK',
  },
  {
    id: 10012,
    customerName: 'Jan Kowalski',
    customerEmail: 'jan.kowalski@mail.pl',
    date: d('2026-08-09'),
    status: 'shipped',
    total: 145.0,
    items: 2,
    country: 'Pologne',
  },
  {
    id: 10013,
    customerName: 'Sara Lindqvist',
    customerEmail: 'sara.l@mail.se',
    date: d('2026-08-08'),
    status: 'delivered',
    total: 278.0,
    items: 3,
    country: 'Suède',
  },
  {
    id: 10014,
    customerName: 'Marco Ferrari',
    customerEmail: 'marco.ferrari@mail.it',
    date: d('2026-08-07'),
    status: 'cancelled',
    total: 55.99,
    items: 1,
    country: 'Italie',
    active: false,
  },
  {
    id: 10015,
    customerName: 'Agnieszka Nowak',
    customerEmail: 'a.nowak@mail.pl',
    date: d('2026-08-06'),
    status: 'delivered',
    total: 399.0,
    items: 5,
    country: 'Pologne',
  },
  {
    id: 10016,
    customerName: 'Erik Johansson',
    customerEmail: 'erik.j@mail.se',
    date: d('2026-08-05'),
    status: 'processing',
    total: 162.75,
    items: 2,
    country: 'Suède',
  },
  {
    id: 10017,
    customerName: 'Lucie Fontaine',
    customerEmail: 'lucie.f@mail.fr',
    date: d('2026-07-30'),
    status: 'delivered',
    total: 89.0,
    items: 1,
    country: 'France',
  },
  {
    id: 10018,
    customerName: 'Hans Müller',
    customerEmail: 'hans.m@mail.de',
    date: d('2026-07-25'),
    status: 'delivered',
    total: 675.0,
    items: 7,
    country: 'Allemagne',
  },
  {
    id: 10019,
    customerName: 'Isabelle Leroy',
    customerEmail: 'i.leroy@mail.be',
    date: d('2026-07-20'),
    status: 'cancelled',
    total: 120.0,
    items: 2,
    country: 'Belgique',
    active: false,
  },
  {
    id: 10020,
    customerName: 'Oliver Smith',
    customerEmail: 'o.smith@mail.co.uk',
    date: d('2026-07-15'),
    status: 'delivered',
    total: 230.5,
    items: 3,
    country: 'UK',
  },
  {
    id: 10021,
    customerName: 'Camille Moreau',
    customerEmail: 'camille.m@mail.fr',
    date: d('2026-07-10'),
    status: 'delivered',
    total: 484.0,
    items: 6,
    country: 'France',
  },
  {
    id: 10022,
    customerName: 'Elena Ivanova',
    customerEmail: 'elena.i@mail.ru',
    date: d('2026-07-05'),
    status: 'shipped',
    total: 310.0,
    items: 4,
    country: 'Portugal',
  },
  {
    id: 10023,
    customerName: 'David Lefebvre',
    customerEmail: 'd.lefebvre@mail.fr',
    date: d('2026-06-28'),
    status: 'delivered',
    total: 55.0,
    items: 1,
    country: 'France',
  },
  {
    id: 10024,
    customerName: 'Chiara Bianchi',
    customerEmail: 'chiara.b@mail.it',
    date: d('2026-06-20'),
    status: 'delivered',
    total: 198.0,
    items: 3,
    country: 'Italie',
  },
  {
    id: 10025,
    customerName: 'Lucas Petit',
    customerEmail: 'lucas.p@mail.fr',
    date: d('2026-06-15'),
    status: 'delivered',
    total: 340.0,
    items: 4,
    country: 'France',
  },
  {
    id: 10026,
    customerName: 'Sofia Hernandez',
    customerEmail: 'sofia.h@mail.es',
    date: d('2026-06-10'),
    status: 'cancelled',
    total: 85.5,
    items: 1,
    country: 'Espagne',
  },
  {
    id: 10027,
    customerName: 'Noah Durand',
    customerEmail: 'noah.d@mail.fr',
    date: d('2026-06-05'),
    status: 'delivered',
    total: 520.0,
    items: 5,
    country: 'France',
  },
  {
    id: 10028,
    customerName: 'Petra Novák',
    customerEmail: 'petra.n@mail.cz',
    date: d('2026-05-28'),
    status: 'delivered',
    total: 175.99,
    items: 2,
    country: 'Tchéquie',
  },
  {
    id: 10029,
    customerName: 'William Hughes',
    customerEmail: 'w.hughes@mail.co.uk',
    date: d('2026-05-20'),
    status: 'delivered',
    total: 620.0,
    items: 8,
    country: 'UK',
  },
  {
    id: 10030,
    customerName: 'Amélie Simon',
    customerEmail: 'amelie.s@mail.fr',
    date: d('2026-05-15'),
    status: 'delivered',
    total: 99.9,
    items: 2,
    country: 'France',
  },
  {
    id: 10031,
    customerName: 'Tobias Becker',
    customerEmail: 't.becker@mail.de',
    date: d('2026-05-10'),
    status: 'delivered',
    total: 289.0,
    items: 3,
    country: 'Allemagne',
  },
  {
    id: 10032,
    customerName: 'Ines Martínez',
    customerEmail: 'ines.m@mail.es',
    date: d('2026-04-30'),
    status: 'delivered',
    total: 157.0,
    items: 2,
    country: 'Espagne',
  },
  {
    id: 10033,
    customerName: 'François Girard',
    customerEmail: 'f.girard@mail.fr',
    date: d('2026-04-20'),
    status: 'delivered',
    total: 895.0,
    items: 9,
    country: 'France',
  },
  {
    id: 10034,
    customerName: 'Charlotte Davies',
    customerEmail: 'c.davies@mail.co.uk',
    date: d('2026-04-10'),
    status: 'delivered',
    total: 412.0,
    items: 5,
    country: 'UK',
  },
  {
    id: 10035,
    customerName: 'Maximilian Braun',
    customerEmail: 'm.braun@mail.de',
    date: d('2026-03-25'),
    status: 'delivered',
    total: 730.0,
    items: 7,
    country: 'Allemagne',
  },
  {
    id: 10036,
    customerName: 'Nathalie Colin',
    customerEmail: 'n.colin@mail.fr',
    date: d('2026-03-15'),
    status: 'delivered',
    total: 66.0,
    items: 1,
    country: 'France',
  },
  {
    id: 10037,
    customerName: 'Andrzej Wiśniewski',
    customerEmail: 'a.w@mail.pl',
    date: d('2026-02-28'),
    status: 'delivered',
    total: 223.5,
    items: 3,
    country: 'Pologne',
  },
  {
    id: 10038,
    customerName: 'Alice Rousseau',
    customerEmail: 'alice.r@mail.fr',
    date: d('2026-02-14'),
    status: 'delivered',
    total: 349.0,
    items: 4,
    country: 'France',
  },
  {
    id: 10039,
    customerName: 'Valentina Conti',
    customerEmail: 'v.conti@mail.it',
    date: d('2026-01-30'),
    status: 'delivered',
    total: 118.0,
    items: 2,
    country: 'Italie',
  },
  {
    id: 10040,
    customerName: 'Hugo Mercier',
    customerEmail: 'hugo.m@mail.fr',
    date: d('2026-01-15'),
    status: 'delivered',
    total: 590.0,
    items: 6,
    country: 'France',
  },
  {
    id: 10041,
    customerName: 'Léa Blanc',
    customerEmail: 'lea.b@mail.fr',
    date: d('2026-08-21'),
    status: 'pending',
    total: 215.0,
    items: 3,
    country: 'France',
  },
  {
    id: 10042,
    customerName: 'Rui Oliveira',
    customerEmail: 'rui.o@mail.pt',
    date: d('2026-08-21'),
    status: 'processing',
    total: 487.5,
    items: 5,
    country: 'Portugal',
  },
  {
    id: 10043,
    customerName: 'Hannah Fischer',
    customerEmail: 'h.fischer@mail.de',
    date: d('2026-08-20'),
    status: 'pending',
    total: 73.0,
    items: 1,
    country: 'Allemagne',
  },
  {
    id: 10044,
    customerName: 'Matteo Romano',
    customerEmail: 'm.romano@mail.it',
    date: d('2026-08-19'),
    status: 'shipped',
    total: 299.0,
    items: 3,
    country: 'Italie',
  },
  {
    id: 10045,
    customerName: 'Cécile Perrin',
    customerEmail: 'cecile.p@mail.fr',
    date: d('2026-08-18'),
    status: 'processing',
    total: 160.0,
    items: 2,
    country: 'France',
  },
];

@Injectable({ providedIn: 'root' })
export class OrdersService {
  getOrders(): Order[] {
    return ORDERS.map((o) => ({ active: true, ...o }) as Order);
  }
}
